### ISSUE TITLE
Update test plan

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/wt-design-docs#117]
We need to update the test plan to include coverage for the following PRs for v0.9:

Dashboard
* [x] Add explicit user selection for asTale parameter [#580](https://github.com/whole-tale/dashboard/pull/580)
* [x] Display repository name instead of URL in publish-modal [#578](https://github.com/whole-tale/dashboard/pull/578)
* [x] Update Publish Modal to support both Zenodo and DataONE  [#576](https://github.com/whole-tale/dashboard/pull/576)
* [x] Allow user to configure DataONE account from User Settings view [#575](https://github.com/whole-tale/dashboard/pull/575)
* [x] User settings additional accounts view [#574](https://github.com/whole-tale/dashboard/pull/574)
* [x] Send 'success' notification upon Tale update. Fixes #566 [#568](https://github.com/whole-tale/dashboard/pull/568)
* [x] Added "Connect Additional Accounts" view [#563](https://github.com/whole-tale/dashboard/pull/563)

Girder Whole tale
* [x] Rename DataONE string [#380](https://github.com/whole-tale/girder_wholetale/pull/380)
* [x] Tale importing and AinWT from Zenodo [#377](https://github.com/whole-tale/girder_wholetale/pull/377)
* [x] Apply some heuristics to make certain datasets look more like a binder [#376](https://github.com/whole-tale/girder_wholetale/pull/376)
* [x] Return a "friendly" repository name in GET /repository. Fixes #374 [#375](https://github.com/whole-tale/girder_wholetale/pull/375)
* [x] Include repository information in Tale's publishInfo [#371](https://github.com/whole-tale/girder_wholetale/pull/371)
* [x] Save globus transfer token without clobbering otherTokens. Fixes #369 [#370](https://github.com/whole-tale/girder_wholetale/pull/370)
* [x] Publish refactor [#367](https://github.com/whole-tale/girder_wholetale/pull/367)
* [x] Add Zenodo external data provider [#365](https://github.com/whole-tale/girder_wholetale/pull/365)
* [x] Add initial support for external accounts [#364](https://github.com/whole-tale/girder_wholetale/pull/364)
* [x] Set Default Category for Tale Imports [#363](https://github.com/whole-tale/girder_wholetale/pull/363)

GWVolman
* [x] [zenodo] use new version for subsequent Tale publications [#98](https://github.com/whole-tale/gwvolman/pull/98)
* [x] Store the DOI as the Tale 'pid' [#97](https://github.com/whole-tale/gwvolman/pull/97)
* [x] Check if the DataONE endpoint already has a v2 [#96](https://github.com/whole-tale/gwvolman/pull/96)
* [x] Add Zenodo publisher and refactor DataONE publisher [#93](https://github.com/whole-tale/gwvolman/pull/93)
* [x] Pass the base_url to dataset/register [#92](https://github.com/whole-tale/gwvolman/pull/92)

**Comment by ThomasThelen** [comment]
I've linked features to test document commits below; I'l leave ticking the boxes off to you if you think they suffice. 

Add explicit user selection for asTale parameter - [Here](https://github.com/whole-tale/wt-design-docs/commit/6fd594ed59cc842d5279827e6465e7dee53d6e46)

Publish refactor, Update Publish Modal to support both Zenodo and DataONE - [Here](https://github.com/whole-tale/wt-design-docs/commit/3714e48dafc992fd24a0321c64e58e1101dd2e5f)

Allow user to configure DataONE account from User Settings view, User settings additional accounts view, Added "Connect Additional Accounts" view - [Here](https://github.com/whole-tale/wt-design-docs/commit/66dcee8e458f6cf9996657a48dc135c5303458a5)
